Update doathing.yml

diff --git a/.github/workflows/doathing.yml b/.github/workflows/doathing.yml
--- a/.github/workflows/doathing.yml
+++ b/.github/workflows/doathing.yml
@@ -10,11 +10,11 @@ jobs:
           echo "$i seconds elapsed"
           sleep 1
         done
-    - name: Fail 20% of the time
-      run: |
-        if [ $((RANDOM % 20)) -eq 0 ]
-        then
-          exit 1
-        fi
-    # - name: fail
-    #   run: exit 1
+    # - name: Fail 20% of the time
+    #   run: |
+    #     if [ $((RANDOM % 20)) -eq 0 ]
+    #     then
+    #       exit 1
+    #     fi
+    - name: succeed
+      run: exit 0
