Update doathing.yml

diff --git a/.github/workflows/doathing.yml b/.github/workflows/doathing.yml
--- a/.github/workflows/doathing.yml
+++ b/.github/workflows/doathing.yml
@@ -1,20 +1,20 @@
-name: Wait 10 minutes and fail 20% of the time
+name: Wait 1 minute and succeed
 on: [pull_request]
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-    - name: Run for 10 minutes
+    - name: Run for 1 minute
       run: |
-        for i in {1..600}; do
+        for i in {1..60}; do
           echo "$i seconds elapsed"
           sleep 1
         done
-    - name: Fail 20% of the time
-      run: |
-        if [ $((RANDOM % 20)) -eq 0 ]
-        then
-          exit 1
-        fi
+    # - name: Fail 20% of the time
+    #   run: |
+    #     if [ $((RANDOM % 20)) -eq 0 ]
+    #     then
+    #       exit 1
+    #     fi
     # - name: fail
     #   run: exit 1
